spring.application.name=SpringEcommApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=postgres
spring.datasource.password=8865004489
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false